apiVersion: apps/v1
kind: Deployment
metadata:
  name: idea-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idea-service
  template:
    metadata:
      labels:
        app: idea-service
    spec:
      containers:
      - name: idea-service
        image: nilsps/idea-service:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_NAME
          value: "brainstorm_db"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_PORT
          value: "5432"
