apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-config
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS ideas (
        id SERIAL PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        description TEXT NOT NULL,
        votes INTEGER DEFAULT 0
    );
