apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
spec:
  template:
    spec:
      containers:
      - name: init-db
        image: postgres:13
        env:
        - name: PGPASSWORD
          value: "postgres"
        command: ["psql", "-h", "postgres", "-U", "postgres", "-d", "brainstorm_db", "-f", "/init.sql"]
        volumeMounts:
        - name: init-script
          mountPath: /init.sql
          subPath: init.sql
      restartPolicy: OnFailure
      volumes:
      - name: init-script
        configMap:
          name: init-db-config
  backoffLimit: 4
