apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting-service
  template:
    metadata:
      labels:
        app: voting-service
    spec:
      containers:
      - name: voting-service
        image: nilsps/voting-service:latest
        ports:
        - containerPort: 5001
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_NAME
          value: "brainstorm_db"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_PORT
          value: "5432"
